import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
export default function Home() {
  const images = []
  return (
    <div className='sm:text-center m-5'>
      <div className={styles.container}>
      <Head>
        <title>2023 ОНЫ ТӨГСӨЛТ "Г" БҮЛЭГ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> 
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         НИЙСЛЭЛИЙН СҮХБААТАР ДҮҮРГИЙН НЭГДҮГЭЭР ДУНД СУРГУУЛИЙН ЗУУН ЖИЛИЙН ТӨГСӨГЧИД, 
         12Г БҮЛЭГ
        </h1>

        <p className={styles.description}>
          Class of '23
        </p>
      </main>

<div>
  <Image src='/nuhurlul.jpg'  width={500} height={500} />
  <Image src='/ulzii.jpeg'  width={500} height={500} />
</div>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
    </div>
    
  )
}
